# Generated by Django 2.1.5 on 2019-01-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190122_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='accounts/static/accounts/default.jpg', upload_to='avatars'),
        ),
    ]
