# Generated by Django 2.1.5 on 2019-01-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=65535),
        ),
    ]
